In [55]:
from IPython.display import Image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
Image(url='http://datascience.uci.edu/wp-content/uploads/sites/2/2014/09/data_science_logo_with_image1.png')

# A Crash Course in Python

Included in this notebook is all of the Python that you should need to complete the tasks during the lessons.  

## Loops in Python

##### For Loop

- https://wiki.python.org/moin/ForLoop
        for x in range(0, 3):
            print "We're on time %d" % (x)

In [56]:
for x in range(0, 3):
    print "We're on time %d" % (x)

We're on time 0
We're on time 1
We're on time 2


##### While Loop
- https://wiki.python.org/moin/WhileLoop
- Beware infinite loops in an iPython Notebook, there's a great chance you won't be able to get out of it.

        collection = ['hey', 5, 'd']
        for x in collection:
            print x

        x = 0
        while x < 10:
            print 'UCI Data Science'
            x += 1

In [57]:
collection = ['hey', 5, 'world']
for x in collection:
    print x

x = 0
y = 10
while (x < 5) & (y==10):
    print 'UCI Data Science'
    x += 1


hey
5
world
UCI Data Science
UCI Data Science
UCI Data Science
UCI Data Science
UCI Data Science


## Mathematics & Linear Algebra

Numpy is a package for scientific computing, that was imported at the top of the notebook as `np`
    
        import numpy as np
        
- http://www.numpy.org/
    
    
### Working with Numpy arrays and Matrices
Numpy has both a function for Numpy matrices `numpy.matrix()` and Numpy Arrays `numpy.array([])`.  It is generally advisable to use numpy arrays over matrices in scientific computing.  

- A comparison between numpy.array() and numpy.matrix()
    - http://wiki.scipy.org/NumPy_for_Matlab_Users
- Another benefit is that pandas DataFrames work well with numpy arrays.
- np.array() Reference: http://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html

###### Creating an Empty Array

In [58]:
np.empty(3)

array([  4.94065646e-324,   9.88131292e-324,   1.48219694e-323])

#####Creating an Array of Ones 

In [59]:
np.ones(3)

array([ 1.,  1.,  1.])

##### Creating an Array of Values

In [60]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

##### Creating a Multi-dimensional Array or Matrix

In [61]:
X = np.array([[1,2,3,4],
              [5,6,7,8]])
print X
print """X has {0} rows, {1} columns""".format(X.shape[0],X.shape[1])

[[1 2 3 4]
 [5 6 7 8]]
X has 2 rows, 4 columns


### Linear Alegebra for Numpy Arrays

##### Matrix multiplication
http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

In [62]:
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])
z = np.array([[2,3,4,5],
              [5,6,7,8]])

print np.multiply(x,y)          # Element-wise multiplication
print np.dot(x,y)               # Matrix/Vector Multiplication
print np.dot(x,z.transpose())   
print np.dot(x,z)               # Notice dimensions matter!

[ 2  6 12 20]
40
[40 70]


ValueError: shapes (4,) and (2,4) not aligned: 4 (dim 0) != 2 (dim 0)

###  Operations on Arrays

- https://scipy-lectures.github.io/intro/numpy/operations.html


#####Taking the sum of a Vector


In [63]:
x = np.array([1,2,3,4])

print np.sum(x)  # Using numpy's sum function
print x.sum()    # Access the objects 'sum' method

10
10


##### Taking the transpose of a Vector or Matrix 

In [64]:
x = np.array([[1,1],[2,2]])

print x 
print x.transpose()
print np.transpose(x)

[[1 1]
 [2 2]]
[[1 2]
 [1 2]]
[[1 2]
 [1 2]]


##### Size and Shape  of an array: 

In [65]:
x = np.array([[1,2,4],
              [3,5,6],
              [1,3,8]])
print x.shape
print x.size
print np.shape(x)
print np.size(x)

(3, 3)
9
(3, 3)
9


#### Linear Algebra Operations in Numpy

Linear Algebra has its own sublibrary, `np.linalg` within Numpy: http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

#####Inverting a Matrix

In [66]:
x = np.array([[1,2,4],
              [3,5,6],
              [1,3,8]])
print np.linalg.inv(x)

[[ 11.   -2.   -4. ]
 [ -9.    2.    3. ]
 [  2.   -0.5  -0.5]]


##### Finding the Norm of a Vector

In [67]:
x = np.array([1,2,3])
y = np.array([[1,2],[1,2]])
print y
print np.linalg.norm(x)
print np.linalg.norm(y)

[[1 2]
 [1 2]]
3.74165738677
3.16227766017


## Matrices and DataFrames in Pandas

- Pandas DataFrames for Design Matrices
    - To create a matrix in Pandas, use the DataFrame method.
        - http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.html
                - matrix = pd.DataFrame({'var1': data1,
                                         'var2': data2})
    - Accessing the columns of a Pandas DataFrame can be done using the columns method 
        - Returning the name of the $i^{th}$ column
            - `matrix.columns[i]`
        - Returning the values of the $i^{th}$ column
            - `matrix[matrix.columns[i]]`
        - Accessing by Colume name
            - `matrix['var1']`

In [1]:
x1 = np.arange(0,10)
x2 = np.arange(0,20,2)
design = pd.DataFrame({'x1':x1,
                       'x2':x2})
print design
print
print 'Column: ', design.columns[1]
print
print design['x1']

NameError: name 'np' is not defined